### PR TITLE
fix: append eval and eval_point to transcript

### LINKED ISSUE #173: A PCS batch opening proof needs to Fiat-Shamir the evaluation claims
In Hyperplonk, after running the sumchecks, the prover needs to generate a batch opening proof for the polynomial evaluations. In the current implementation:
https://github.com/EspressoSystems/hyperplonk/blob/main/hyperplonk/src/snark.rs#L610
https://github.com/EspressoSystems/hyperplonk/blob/main/subroutines/src/pcs/multilinear_kzg/batching.rs#L209
the Fiat-Shamir transcript (for generating the random challenge t) doesn't include the evaluation claims (i.e., the evaluation points and the evaluation values). This would be insecure, as an attacker can adaptively choose the evaluation values after knowing the challenge t.

Action items:
1. Fiat-shamir the evaluation values of the evaluation claims before batching.
2. Fiat-shamir the random evaluation point as well. (I didn't see an immediate attack without doing this, but I think it's safer to do so.)

cc @alxiong @mrain @zhenfeizhang

### PR DESCRIPTION
**Pull request by alxiong**
Closes #173 

### This PR:

Append `eval` and `eval_points` to FS transcript before doing the batch opening (or the verification) to prevent malicious prover attack.

### CODE REVIEW

File: hyperplonk/src/snark.rs [hunk 1]
```diff
@@ -337,6 +337,12 @@ where
         // =======================================================================
         // 5. deferred batch opening
         // =======================================================================
+        for eval_point in pcs_acc.points.iter() {
+            transcript.append_serializable_element(b"eval_point", eval_point)?;
+        }
+        for eval in pcs_acc.evals.iter() {
```
Comment (chancharles92) [inline hyperplonk/src/snark.rs:343]: Maybe it's better to put this line into pcs.multi_open(.) instead, because we always need to FS the evaluation value in a batching proof.

File: hyperplonk/src/snark.rs [hunk 2]
```diff
@@ -605,6 +611,22 @@ where
         end_timer!(pi_step);
 
         end_timer!(step);
+
+        for eval_point in points.iter() {
+            transcript.append_serializable_element(b"eval_point", eval_point)?;
+        }
+        for eval in prod_evals
```
Comment (chancharles92) [inline hyperplonk/src/snark.rs:618]: Similarly, it might be better to put it to PCS::batch_verify(.)

**Review by chancharles92 — COMMENTED** [review]
Thanks @alxiong ! Added some comments. Should be easy to address.

File: hyperplonk/src/snark.rs (hunk 1 above)
Comment (alxiong) [reply hyperplonk/src/snark.rs:343]: wait, just to confirm, you want to only put "append evals" to `multi_open()` but not "append eval_points"? I find it confusing. it makes sense to put all my code addition to PCS batch open (and verify).

Comment (chancharles92) [reply hyperplonk/src/snark.rs:343]: There is no need to Fiat-Shamir the evaluation points when they're fixed. But yes, we can also choose to Fiat-Shamir them by default.

Comment (alxiong) [reply hyperplonk/src/snark.rs]: done in [e58574f](https://github.com/EspressoSystems/hyperplonk/pull/174/commits/e58574fda5b8f45b3bbf2c6745b09214c04b26f3)

File: hyperplonk/src/snark.rs (hunk 2 above)
Comment (alxiong) [reply hyperplonk/src/snark.rs]: done in [e58574f](https://github.com/EspressoSystems/hyperplonk/pull/174/commits/e58574fda5b8f45b3bbf2c6745b09214c04b26f3)

**Review by chancharles92 — APPROVED** [review]
Thanks @alxiong !
